version: "3.3"
services:
  mqtt:
    container_name: mqtt
    restart: unless-stopped
    image: eclipse-mosquitto
    volumes:
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - devices
  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - "3000:80"
    volumes:
      - ./server:/app
    environment:
      - MQTT_HOST=mqtt
      - MQTT_CLIENT_ID=controller
    command: npx nodemon bin/www --ignore garage-state.json
    networks:
      - frontend
      - devices
  switch:
    container_name: garage-switch
    build:
      context: ./mqtt-switch
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=development
    command: npx nodemon garage.mqtt.js
    volumes:
      - ./mqtt-switch:/app
    environment:
      - MQTT_HOST=mqtt
      - MQTT_CLIENT_ID=garage-door-switch
    networks:
      - devices
networks:
  frontend:
  devices:
